import type { Metadata } from "next";
import localFont from 'next/font/local'
import './globals.css'

// 使用系统字体
const systemFonts = {
  variable: "--font-geist-sans",
};

const monoFonts = {
  variable: "--font-geist-mono",
};

// 添加思源宋体
const sourceHanSerif = localFont({
  src: '../../public/fonts/SourceHanSerifCN-Regular.ttf',
  variable: '--font-source-han-serif',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceHanSerif.variable} antialiased`}
        style={{
          '--font-geist-sans': '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
          '--font-geist-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        } as React.CSSProperties}
      >
        {children}
      </body>
    </html>
  );
}