import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import localFont from 'next/font/local'
import './globals.css'

const inter = Inter({
  variable: "--font-geist-sans", // 保持变量名不变，以避免更多修改
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono", // 保持变量名不变，以避免更多修改
  subsets: ["latin"],
});

// 添加思源宋体
const sourceHanSerif = localFont({
  src: '../../public/fonts/SourceHanSerifCN-Regular.ttf',
  variable: '--font-source-han-serif',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} ${sourceHanSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}